#!/bin/bash
ghci src/Interpreter.hs \
	-package mtl \
	-i build/AbsGrammar \
	-i build/LexGrammar \
	-i build/ParGrammar \
	-i build/ErrM \
	-i src/TypeChecker.hs \
	-i src/Run.hs \
	-i src/CommonDeclarations.hs \
	-i src/Expressions.hs \
	-i src/Statements.hs \
